### ISSUE TITLE
UI update requests to Patro extension

### ISSUE THREAD

**Issue by sumanchapai** [sumanchapai/patro#9]
<img width="370" alt="image" src="https://github.com/sumanchapai/patro/assets/26862106/d32bbcdf-6fef-49e4-be39-1b779aaed0d4">

It would be great if we had the "TODAY" button (or something of the sort) so that people that people could click on to get to today... and also making today's color to be something different would be nice… just copy ideas from hamropatro app...

it would be nice if the tihis were displayed with the numbers like in hamropatro

**Comment by paudsu01** [comment]
I have pushed that change to the chrome-extension branch. However, I will add the date conversion feature and make a pull request. As of now, it looks like this : 
<img width="350" alt="image" src="https://github.com/sumanchapai/patro/assets/114323952/9c6ec717-ee16-4eba-8556-0ee736a74704">
